---
title: "Inequality Map"
author: "Megan Wylie"
date: '2020-01-02'
categories: ["R"]
tags: ["R Markdown", "plot"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F )

library(tidyverse)
library(geojsonio)
library(sf)
#library(mapview)
library(leaflet)
library(shiny)
library(rgdal)

point.locations.sf <- read_rds("data/canada_city_inequality_sf.RDS")

```

# Income inequality and health research

I wrote my Master's thesis on the topic of income inequality and health in Canadian cities. To show inequality throughout Canada, I mapped inequality levels for each Canadian city for three time periods: 2001, 2006, and 2011.

Here is a reproduction of that map, which now includes 2016.

# Map

```{r , echo = F}
# Name cities
# mapview::mapview(point.locations.sf, label = point.locations.sf$CMANAME)

point.locations.sf.transform <- sf::st_transform(point.locations.sf , 4326)

# make quintiles to bin the gini coefficients
tf <- point.locations.sf.transform %>% 
  left_join(point.locations.sf.transform %>% 
              as.tibble() %>% 
              select(CMANAME , gini01 , gini06 , gini11 , gini16) %>% 
              mutate_at(c("gini01" , "gini06" , "gini11" , "gini16") , dplyr::percent_rank) %>% 
              mutate(gini01_bin = if_else(gini01 > .75 , 4 , 
                                          if_else(gini01 > .5 , 3 , 
                                                  if_else(gini01 > .25 , 2 , 1))), 
                     gini06_bin = if_else(gini06 > .75 , 4 , 
                                          if_else(gini06 > .5 , 3 , 
                                                  if_else(gini06 > .25 , 2 , 1))),
                     gini11_bin = if_else(gini11 > .75 , 4 , 
                                          if_else(gini11 > .5 , 3 , 
                                                  if_else(gini11 > .25 , 2 , 1))),
                     gini16_bin = if_else(gini16 > .75 , 4 , 
                                          if_else(gini16 > .5 , 3 , 
                                                  if_else(gini16 > .25 , 2 , 1))),
              ) %>% select(CMANAME , gini01_bin , gini06_bin
                           , gini11_bin , gini16_bin) , 
            by = "CMANAME")

#set up legend pallette 
#pal <- colorBin("PuOr", df$z, bins = c(0, .1, .4, .9, 1))

#was trying ex from here: https://github.com/aagarw30/R-Leaflet-Tutorial/blob/master/CircleMarker_Pallete/CircleMarkerColor.R
#pal2 = colorFactor(palette = c("yellow", "red", "black", "green"),
               #    domain=tf$gini16_bin)

# map via leaflet

leaflet(tf) %>% 
  addProviderTiles(provider = providers$CartoDB.Positron) %>%
  #addCircleMarkers defines size in terms of metres - they're too similar in size
  addCircleMarkers(#radius = 50*(qlogis(point.locations.sf.transform$gini01)),
                   color = "#3182bd" ,
                   fillColor = "#9ecae1" ,
                   fillOpacity = .6 , 
                   radius = ~ gini01_bin*2 ,
                   weight = 2 ,
                   label = ~paste(CMANAME , round(gini01, digits = 2) , sep = ", " ),
                   group = "Gini Coefficient 2001") %>% 
  addCircleMarkers( color = "#3182bd" ,
                    fillColor = "#9ecae1" ,
                    fillOpacity = .6 , 
                    radius = ~ gini06_bin*2 ,
                    weight = 2 ,
                    label = ~paste(CMANAME , round(gini06, digits = 2) , sep = ", "),
                    group = "Gini Coefficient 2006") %>% 
  addCircleMarkers( color = "#3182bd" ,
                  fillColor = "#9ecae1" ,
                  fillOpacity = .6 , 
                  radius = ~ gini11_bin*2 ,
                  weight = 2 ,
                  label = ~paste(CMANAME , round(gini11, digits = 2) , sep = ", " ) ,
                  group = "Gini Coefficient 2011") %>%
  addCircleMarkers( color = "#3182bd" ,
                    fillColor = "#9ecae1" ,
                    fillOpacity = .6 , 
                    radius = ~ gini16_bin*2 ,
                    weight = 2 ,
                    label = ~paste(CMANAME , round(gini16, digits = 2), sep = ", " ),
                    group = "Gini Coefficient 2016") %>%
  #addLayersControl command breaks each year into one selection option.
  addLayersControl(
                overlayGroups = c("Gini Coefficient 2001", "Gini Coefficient 2006" ,
                             "Gini Coefficient 2011" , "Gini Coefficient 2016")) %>% 
  #add legends that appear/disappear with toggle
        #addLegend (pal = pal, values = ~ gini01_bin, 
         #          group = "Gini Coefficient 2001", 
          #          title = "City Gini Coefficient 2001") %>% 
        #addLegend (pal = pal, values = ~ gini06_bin, 
         #          group = "Gini Coefficient 2006", 
          #          title = "City Gini Coefficient 2006") %>% 
        #addLegend (pal = pal, values = ~ gini11_bin, 
         #          group = "Gini Coefficient 2011", 
          #          title = "City Gini Coefficient 2011") %>% 
        #addLegend (pal = pal, values = ~ gini16_bin, 
         #          group = "Gini Coefficient 2016", 
          #          title = "City Gini Coefficient 2016") %>% 
  #hide layers 2001, 2006, and 2011 for when the map opens. 
  hideGroup("Gini Coefficient 2001") %>% 
              hideGroup("Gini Coefficient 2006") %>% 
            hideGroup("Gini Coefficient 2011")

# I still need to change the legend values to the Gini Coefficient values. 


```



